version: '3.8'

services:
  olap_db:
    image: postgres:14
    environment:
      POSTGRES_DB: olap_db
      POSTGRES_USER: olap_user
      POSTGRES_PASSWORD: olap_password
    volumes:
      - ./task2/olap/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U olap_user -d olap_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      KEYCLOAK_ISSUER: http://localhost:8080/realms/reports-realm
      KEYCLOAK_JWKS_URL: http://keycloak:8080/realms/reports-realm/protocol/openid-connect/certs
      OLAP_DSN: postgresql://olap_user:olap_password@olap_db:5432/olap_db
    depends_on:
      olap_db:
        condition: service_healthy
      keycloak:
        condition: service_started
  airflow:
    build:
      context: ./task2/airflow
      dockerfile: Dockerfile
    command: ["airflow", "standalone"]
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_CONN_OLAP: postgresql://olap_user:olap_password@olap_db:5432/olap_db
    volumes:
      - ./task2/airflow/dags:/opt/airflow/dags
    depends_on:
      olap_db:
        condition: service_healthy
    user: "50000:0"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_KEYCLOAK_URL: http://localhost:8080
      REACT_APP_KEYCLOAK_REALM: reports-realm
      REACT_APP_KEYCLOAK_CLIENT_ID: reports-frontend
    depends_on:
      - backend
